using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Soenneker.Quark.Gen.Tailwind.Modifiers;

[Generator]
public sealed class TailwindModifiersGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Soenneker.Quark.TailwindModifiersAttribute";

    private static readonly string[] ModifierProperties =
    {
        "OnHover",
        "OnFocus",
        "OnFocusVisible",
        "OnActive",
        "OnDisabled",
        "OnDark",
        "OnVisited",
        "OnChecked",
        "OnOpen",
        "OnFirst",
        "OnLast",
        "OnOdd",
        "OnEven",
        "OnBefore",
        "OnAfter",
        "OnPlaceholder",
        "OnSelection",
        "OnMarker",
        "OnFirstLetter",
        "OnFirstLine",
        "OnFile",
        "OnBackdrop",
        "OnGroupHover",
        "OnGroupFocus",
        "OnPeerHover",
        "OnPeerFocus"
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource("TailwindModifiersAttribute.g.cs", AttributeSource));

        IncrementalValuesProvider<ModifierCandidate?> candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
            static (ctx, _) => GetModifierCandidate(ctx))
            .Where(static candidate => candidate is not null);

        context.RegisterSourceOutput(candidates.Collect(), static (ctx, candidates) =>
        {
            ImmutableArray<ModifierCandidate> modifiers = candidates.Where(static candidate => candidate is not null)
                                                                     .Select(static candidate => candidate!.Value)
                                                                     .Distinct()
                                                                     .OrderBy(static candidate => candidate.FullTypeName, StringComparer.Ordinal)
                                                                     .ToImmutableArray();

            foreach (ModifierCandidate modifier in modifiers)
            {
                string hintName = modifier.FullTypeName.Replace("global::", string.Empty)
                                      .Replace(".", "_")
                                      .Replace("+", "_") + ".TailwindModifiers.g.cs";

                ctx.AddSource(hintName, GenerateModifierSource(modifier));
            }
        });
    }

    private static ModifierCandidate? GetModifierCandidate(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax) context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol typeSymbol)
            return null;

        AttributeData? attribute = null;

        foreach (AttributeData attr in typeSymbol.GetAttributes())
        {
            INamedTypeSymbol? attrClass = attr.AttributeClass;

            if (attrClass is null)
                continue;

            if (string.Equals(attrClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + AttributeMetadataName, StringComparison.Ordinal) ||
                string.Equals(attrClass.ToDisplayString(), AttributeMetadataName, StringComparison.Ordinal))
            {
                attribute = attr;
                break;
            }
        }

        if (attribute is null || attribute.ConstructorArguments.Length == 0 || attribute.ConstructorArguments[0].Value is not INamedTypeSymbol builderType)
            return null;

        string? ns = typeSymbol.ContainingNamespace is { IsGlobalNamespace: false } containingNamespace
            ? containingNamespace.ToDisplayString()
            : null;

        var containingTypes = new Stack<string>();
        INamedTypeSymbol? containingType = typeSymbol.ContainingType;

        while (containingType is not null)
        {
            containingTypes.Push(containingType.Name);
            containingType = containingType.ContainingType;
        }

        return new ModifierCandidate(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            builderType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            ns,
            containingTypes.ToImmutableArray());
    }

    private static string GenerateModifierSource(ModifierCandidate candidate)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (candidate.Namespace is { Length: > 0 })
        {
            sb.Append("namespace ");
            sb.Append(candidate.Namespace);
            sb.AppendLine(";");
            sb.AppendLine();
        }

        for (var i = 0; i < candidate.ContainingTypes.Length; i++)
        {
            sb.Append("partial class ");
            sb.Append(candidate.ContainingTypes[i]);
            sb.AppendLine();
            sb.AppendLine("{");
        }

        sb.Append("public static partial class ");
        sb.Append(candidate.TypeName);
        sb.AppendLine();
        sb.AppendLine("{");

        for (var i = 0; i < ModifierProperties.Length; i++)
        {
            string property = ModifierProperties[i];
            sb.Append("    public static ");
            sb.Append(candidate.BuilderTypeName);
            sb.Append(' ');
            sb.Append(property);
            sb.Append(" => new ");
            sb.Append(candidate.BuilderTypeName);
            sb.Append("().");
            sb.Append(property);
            sb.AppendLine(";");
        }

        sb.AppendLine("}");

        for (var i = 0; i < candidate.ContainingTypes.Length; i++)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private const string AttributeSource = """
// <auto-generated/>
#nullable enable

namespace Soenneker.Quark;

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal sealed class TailwindModifiersAttribute : global::System.Attribute
{
    public TailwindModifiersAttribute(global::System.Type builderType)
    {
        BuilderType = builderType;
    }

    public global::System.Type BuilderType { get; }
}
""";

    private readonly struct ModifierCandidate : IEquatable<ModifierCandidate>
    {
        public ModifierCandidate(string typeName, string fullTypeName, string builderTypeName, string? ns, ImmutableArray<string> containingTypes)
        {
            TypeName = typeName;
            FullTypeName = fullTypeName;
            BuilderTypeName = builderTypeName;
            Namespace = ns;
            ContainingTypes = containingTypes;
        }

        public string TypeName { get; }
        public string FullTypeName { get; }
        public string BuilderTypeName { get; }
        public string? Namespace { get; }
        public ImmutableArray<string> ContainingTypes { get; }

        public bool Equals(ModifierCandidate other) =>
            string.Equals(TypeName, other.TypeName, StringComparison.Ordinal) &&
            string.Equals(FullTypeName, other.FullTypeName, StringComparison.Ordinal) &&
            string.Equals(BuilderTypeName, other.BuilderTypeName, StringComparison.Ordinal) &&
            string.Equals(Namespace, other.Namespace, StringComparison.Ordinal) &&
            ContainingTypes.SequenceEqual(other.ContainingTypes);

        public override bool Equals(object? obj) => obj is ModifierCandidate other && Equals(other);

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = (hash * 31) + StringComparer.Ordinal.GetHashCode(TypeName);
                hash = (hash * 31) + StringComparer.Ordinal.GetHashCode(FullTypeName);
                hash = (hash * 31) + StringComparer.Ordinal.GetHashCode(BuilderTypeName);
                hash = (hash * 31) + (Namespace is null ? 0 : StringComparer.Ordinal.GetHashCode(Namespace));

                for (var i = 0; i < ContainingTypes.Length; i++)
                    hash = (hash * 31) + StringComparer.Ordinal.GetHashCode(ContainingTypes[i]);

                return hash;
            }
        }
    }
}
